{{- if not .Values.persistence.data.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bookorbit.fullname" . }}-data
  labels:
    {{- include "bookorbit.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
