#!/usr/bin/env bash
set -euo pipefail

OUT="my-secrets.yaml"

if [[ -f "$OUT" ]]; then
  echo "$OUT already exists; skipping. Delete it and re-run to regenerate secrets." >&2
  exit 0
fi

cat > "$OUT" <<EOF
# my-secrets.yaml — generated by scripts/gen-secrets.sh
# Do not commit this file. It is listed in .gitignore.
credentials:
  postgresPassword: "$(openssl rand -hex 24)"
  jwtSecret: "$(openssl rand -hex 32)"
  setupBootstrapToken: "$(openssl rand -hex 16)"
EOF

echo "Generated $OUT."
echo "You can install from source with:"
echo "  helm upgrade --install bookorbit ./charts/bookorbit --namespace bookorbit --create-namespace -f $OUT"
